### PR TITLE
Boltron with systemd

### PR DESCRIPTION
**Pull request by TomasTomecek**
TODO:
 - [x] make it work with SELinux

You can test with:

```
$ git clone -b boltron-with-systemd https://github.com/TomasTomecek/dnf-modularity-prototype
$ cd dnf-modularity-prototype
$ make build
$ make run-systemd
```

### CODE REVIEW

**Comment by TomasTomecek** [comment]
updated: it should work with SELinux now

**Comment by james-antill** [comment]
So I merged the first part of this, but was holding off on the second part as I wanted to fix it by having the module be the DNF bits eventually ... is this causing problems?

**Comment by james-antill** [comment]
This is basically done now, moved my local stuff to a different file.

**Comment by TomasTomecek** [comment]
Thanks, James!

**Pull request closed without merging**
